version: '3'

services:
    mysql5.7:
        image: mysql:5.7
        volumes:
            - mysql5.7-data:/var/lib/mysql
            - ./mysql-mount/imports:/var/imports
            - ./mysql-mount/exports:/var/exports
        ports:
            - "3307:3306"
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mysql5.6:
        image: mysql:5.6
        volumes:
            - mysql5.6-data:/var/lib/mysql
            - ./mysql-mount/imports:/var/imports
            - ./mysql-mount/exports:/var/exports
        ports:
            - "3308:3306"
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mysql5.5:
        image: mysql:5.5
        volumes:
            - mysql5.5-data:/var/lib/mysql
            - ./mysql-mount/imports:/var/imports
            - ./mysql-mount/exports:/var/exports
        ports:
            - "3309:3306"
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    mysql8.0.15:
        image: mysql:8.0.15
        volumes:
            - mysql8.0.15-data:/var/lib/mysql
            - ./mysql-mount/imports:/var/imports
            - ./mysql-mount/exports:/var/exports
        ports:
            - "3310:3306"
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    pg11.2:
        image: postgres:11.2-alpine
        volumes:
            - pg11.2-data:/var/lib/postgresql/data
            - ./pg-mount/imports:/var/imports
            - ./pg-mount/exports:/var/exports
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mysql5.7-data:
    mysql5.6-data:
    mysql5.5-data:
    mysql8.0.15-data:
    pg11.2-data:
